---
title: "Upscaling the resilience assessment through comparative analysis"
author: |
    | \small Juan Rocha^1,2,3^, Carla Lanyon^1^, Miriam Huitric^1^, Garry Peterson^1^
    | \small
    | \small ^1^Stockholm Resilience Centre, Stockholm University, Kräftriket 2B, 10691 Stockholm
    | \small ^2^Future Earth, The Swedish Royal Academy of Sciences, Lilla Frescativägen 4A, 104 05 Stockholm
    | \small ^3^South American Institute for Resilience and Sustainability Studies, Maldonado, Uruguay




abstract: |
  Panarchy has marked the academic career of many scholars and practitioners facing environmental problems. Initially introduced as a conceptual framework and set of metaphors, panarchy has gained the attention of scholars across many disciplines and its ideas continue to inspire further conceptual developments. To what extent these concepts have developed, theorized and empirically grounded are questions we address by reviewing the literature with qualitative methods and machine learning. We find that the adaptive cycle is the feature of panarchy that has attracted more attention. Challenges remain in empirically grounding the metaphor, but recent theoretical and empirical work offer some avenues for future research.

bibliography: panarchy.bib
# csl: nature.csl
output:
  pdf_document:
    dev: pdf
    keep_tex: no
    toc: no
    latex_engine: xelatex
  word_document:
    toc: no
citecolor: blue
documentclass: article
font: Arial
fontsize: 10pt

linkcolor: blue
urlcolor: blue
header-includes:
- \usepackage{dcolumn, rotating, longtable, lineno, float, fontspec, array, tabularx}
- \setmainfont{Arial}
- \linenumbers
- \renewcommand{\abstractname}{}
- \graphicspath{{figures/}}
- \usepackage[margin=2.5cm]{geometry}
---

# Outline:

- Intro (800)
    - Resilience: what it is? how is it measured?
    - Current options: resilience assessemnts.
    - Quantitative approaches: time series, luxury data
    - Alternatives beyond single case studies?
- Methods (600)
    - ARR: Transdisciplinary process
    - Template co-design
    - Case study selection
    - QCA
- Results (1000)
    - Descriptive states: 30-35 cases: time and spatial scales. Regions / countries. Drivers and challenges
    - Calibration steps
    - Resilience as output: necessary and sufficient conditions
    - Loss of resilience as output: necessary and sufficient conditions
- Discussion (1000)
    - Why we develop a third-tier of variables: Berkes alone or Biggs alone was not enought, too ambiguous to assign precise coding.
    - Low number of transformation cases limits the application of the method
    - Leveraging the power of comparison.
- Conclusions (400)

# Introduction

[800w]

Resilience is the capacity of any system to absorb disturbance and reorganize while undergoing change so as to still retain essentially the same function, structure, feedbacks, and therefore identity [@Anonymous:2016fv]. There are over 70 definitions of resilience [], making it a hard concept to grasp, to operationalize, and empirically ground. How does one measure resilience remains a non-trivial challenge and a key frontier of active research [].

Seminal and foundational work on resilience emerged from reflections about ecological stability [] and the possibility that ecosystems can undergo regime shifts []. Regime shifts are abrupt and persistent changes in the function and structure of systems []. Thus if regime shifts relate to the possibility that a system can exist in multiple configurations, resilience is the ability to keep a system within a particular configuration. They are two complementary sides of the same coin. Not surprisingly, early theoretical work attempting to operationalize measures of resilience focused on metrics such as the size of the basin of attraction, its depth, slope, or proximity to the boundary that separate different regimes []. More recent endavours of approximating resilience from that perspective suffer from the problem of finding sufficient observables [], or high quality data to characterize multidimensional configurations of social-ecological systems [].

While resilience is often introduced in the context of ecological problems, its roots go beyond ecology. In fact, the use of the term in the social sciences precedes its use in ecology (Fig 1), and the ideas of multiple attractors would have not been possible without the development of bifurcation theory in mathematics almost a century and a half ago []. Bifurcations have found applications in the theories of poverty traps already in the 1950s, segregation in sociology by the 1970s, and over the last half century in fields that span medicine, climate science, linguistics, finance or physics, to name a few [].

If these concepts are so widely used, why is it so hard to find good empirical proxies of resilience? One problem with the general applicability of these concepts is that applying it to different systems requires answering a priori the questions of resilience of what to what? []. Doing so reduces the ability to comparing across systems. For example, one might successfuly approximate the resilience of a cancer, but it does not mean one can use the same method or proxies to assess the resilience of climate, or not even a different type of cancer. Consequently, most resilience assessments have been centered around particular problems by particular actors (e.g. water management), and remain participatory consultations limited by the perceptions of participants. They are important exercises to generate shared knowledge of a management problem enabling communities to identify feedbacks, slow variables or potential leverage points for intervention [@ResilienceAlliance:2011vc; @Walker:2012wp; @Walker:2012ur]. Yet, more generic, cross-system approaches are needed [@Scheffer:2012cta; @Scheffer:2003p339; @Scheffer:2009p4449].

Time being a common dimension to any dynamical system lends itself for the development of generic proxies of resilience [@Scheffer:2009p4449], in particular recovery time []. Complex systems when close to critical transitions leave statistical signatures on the time series of its state variables known as critical slowing down [@Strogatz:2014wo; @Scheffer:2012cta; @Scheffer:2009p4449]. It means that the system takes longer to recover after a small disturbance, which translates into increases in variance, autocorrelation, and skewness or flickering [@Scheffer:2009p4449; @Dakos:2015jt]. These methods however have some limitations. They can fail when dynamics are driven by stochastic processes [@Hastings:2018gy; @Hastings:2010p5336], and often require long time series to detect useful signals [@Dakos:2015jt]. Time-based metrics offer no insight in other important dimensions of resilience: adaptive and transformative capacities.

Here we propose a qualitative comparative method for upscaling resilience assessments. We study 35 communities in the Arctic facing environmental and social challenges related to potential regime shifts in Arctic ecosystems, or socio-economic and political pressures opened by recent pathways of development. We outline how leveraging the power of comparison enable extracting patterns that transcend individual case studies informing theory development, as well as potential management or governance arrangements. We hope our qualitative proposal complements current quantitative metrics that focus on recovery time by gaining insights about the ability to adapt and transform that define communities in the Arctic. But why the Arctic?

The Arctic is a region of the world where the resilience of communities is being tested at a extreme. Climate change alone is impacting Arctic ecosystems ~4 times faster than the rest of the globe []. Climate impact is greater than ice loss, fundamentally changing landscape and seascape connectivity, the flow of energy and nutrients, and structure and function of biological communities. The Arctic is also the scene of vast socio-economic changes and challenges []. The reduction of Arctic sea ice is opening the possibility for mining exploration and new international shipping routes [], increase in pollution [] or changing conditions for fisheries and aquaculture []. Securing basic food, water and energy, as well as diversifying economies, remain key human development challenges for Arctic communities [].

How can Arctic communities respond to these social and ecological challenges? Will they adapt and continue with their traditional livelihoods, or transform towards new social-ecological configurations?

# Methods

[600w]

To answer these questions we first revisited the literature on adaptive capacity and designed a coding scheme for capturing elements of resilience across case studies. We co-designed and co-developed a template to guide case study selection, literature reviews, and validation with experts. Then we applied qualitative comparative analysis to infer necessary and sufficient conditions for resilience, transformations or resilience loss in 35 communities across the Arctic. Below we describe in detail each of these steps.

**Measuring adaptive capacity**: We draw inspiration from early conceptual developments on how to approximate adaptive capacity. Adaptability is related to the capacity to learn, combine experience and knowledge, innovate, and adjust responses and institutions to changing external drivers and internal processes [@Anonymous:2016fv]. Berkes et al [-@Berkes:2003wx] proposed a two-tier set of variables grouped around four key dimensions: i) learning to live with change and uncertainty (NAV), ii) nurturing diversity for reorganization and renewal (DIV), iii) combining different types of knowledge for learning (KNO), and iv) creating opportunities for self organization (SFO). We complemented the two-tier approach with a third-tier of variables (Table X) by combining recent developments on principles for building resilience [@Anonymous:2011iw] with expert knowledge elicitation. The refining of our third-tier of variables benefited from input and testing of preliminary case studies in the context of the Arctic Resilience Assessment [@Carson:2016ts].

The Arctic Resilience Assessment was commissioned by the Arctic council under the Swedish Ministry of Environment chairmanship of the council, and delivered under the US chairmanship. The assessment was lead by the Stockholm Resilience Centre and the Stockholm Environmental Institute and builds on collaborations between the Arctic countries, Indigenous peoples in the region, and several observers that include NGOs and academic institutions. Table X presents the different interest groups represented in the process.

**Co-designing a case study template**: We initially designed a template to capture social-ecological dynamics from literature review and expert elicitation inspired by the Regime Shifts database []. Our first template was however modified to incorporate the feedback, needs and priorities of the different actor involved (Table X). We modified and tested the gathering data tool through workshops and focus groups that took place in Washigthon, Tromsø, Bodø, and Stockholm (2015-16). The group also guided our selection of case studies to prioritize their most acute needs, and secure an heterogeneous selection of studies across problem issues and geographies.

The template was designed to capture key aspects of resilience and adaptive capacity based on literature review. The coder assigns whether the social-ecological system is resilient if the main livelihoods of the communities described are maintained over time, despite social and ecological disturbances. A case is coded as transformation if a community shift their main source of livelihoods to a different set, but manages to continue developing within the same place. A case is coded as loss of resilience where the main livelihoods are lost, no new livelihoods are established, and symptoms of community collapse long last such as emigration, simplified local economies, high unemployment or high substance abuse. When possible, the templates were validated by experts in the topics who suggested new literature sources or improve our interpretation of the initial review. All templates collected are available in <XYZ> data repository.

**Qualitative comparative analysis**: Based on the templates, we coded a matrix of presence / absence of the third-tier variables used as proxies of adaptive capacity (Table X). A category is coded as -1 if the evidence in the literature or expert elicitation suggest that the case lacks that dimension, 1 if the evidence suggest presence of the category, or 0 if there is no evidence available. We aggregated the scores at the first-tier level by summing across the the third-level categories. Qualitative comparative analysis was then used to investigate necessary and sufficient conditions for a case to be resilient, transformation, or loss of resilience.

Qualitative comparative analysis (QCA) is a method that leverage boolean algebra [] and set theory to investigate research questions with intermediate number of cases []. While its origins are rooted in political science and sociology, the method has found application in several social-ecological systems problems []. In our analysis, the four dimensions for adaptive capacity [] were used as conditions, and the outputs were coded as resilience loss, transformation or resilience based on the templates. First, we calibrated thresholds for inclusion or exclusion of conditions based on the distribution features of the categories. Next, we computed subsets of necessary and sufficient conditions for each possible output and its negation. We used the truth table of our case studies --a cross tabulation of the number of cases in our sample against all possible combinations of conditions and outputs-- to perform bolean minimization and identify parsimonious, complex, and intermediate solutions. These solutions (or causal recipes in the literature) suggest combination of conditions that leads to an output (being resilient) to be true or false. In other words, it helps us identify which features increase adaptive capacity, and hence resilience, in the Arctic communities in our study.

# Results

1000w

Truth table should come early

* Figure 1. Map of cases
* Figure 2. Heatmaps 1-2-3 tiers
* Figure 3. Distribution of codings + calibration thresholds.
* Figure 4. Necessary and Sufficient conditions for resilience
* Figure 5. Necessary and sufficient conditions for rersilience loss
*


# Discussion
(1000w)

- Principles for building resilience didnt work.
- The aggregation by summing has the implicit assumption that all categories are equally weighted. That is, the researcher does not have an apriori bias or inclination to decide which variables could be more important than others for adaptive capacity. As theory develops, one could relax such assumption.
# Conclusion
(400w)


# Acknowledgements
- All case contributors
- All workshop participants
- Arctic council

# References

<div id="refs"></div>



\pagebreak

# Supplementary Material {#sec:SM}

\renewcommand\thefigure{S\arabic{figure}}
\renewcommand\thetable{S\arabic{table}}
\setcounter{table}{0}
\setcounter{figure}{0}
